### ISSUE TITLE
Installation (rails generate) leads to error

### ISSUE THREAD

**Issue by sebastianjonas** [madzhuga/rails_workflow#1]
I created a new project with rails 4.1.9 (ruby 2.1.5).
Gemfile is standard. Added the line "gem 'rails_workflow', '0.2.1'". 
After bundle install I added the line 
        mount RailsWorkflow::Engine => '/workflow', as: 'workflow'
in routes.rb.
After executing "rails generate rails_workflow:install" the first error was 

   /.rvm/gems/ruby-2.1.5@railsworkflow/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- devise (LoadError)

I added devise in the gemfile (gem 'devise'). After the next bundle install the following error appeared:

/.rvm/gems/ruby-2.1.5@railsworkflow/gems/rails_workflow-0.2.1/config/initializers/will_paginate.rb:8:in `<module:ActionView>': uninitialized constant WillPaginate::ActionView::LinkRenderer (NameError)

**Comment by madzhuga** [comment]
I fixed both errors in master branch already. Going to build 0.3 gem version shortly.

**Comment by madzhuga** [comment]
fixed in 0.2.2 version
