### ISSUE TITLE
Not able to achieve parallel processing

### ISSUE THREAD

**Issue by waleedjaffar** [madzhuga/rails_workflow#10]
Details below:
1. Create a new Process Template
2. Click on Add Operation and create a role based operation (eg. Approval by Team Lead)
3. Click on Add Operation and create another role based operation (eg. Approval by Manager) and do not select dependency check box
4. Click on Add Operation and create a third role based operation (eg. Approval by Delivery Manager) and select dependencies as:
* Approval by Team Lead - Done
* Approval by Manager - Done

5. Modify application by mapping above created process template id
6. Login with user who has _Team lead_ role
* Click on _User Operations_ link.
* Under _Available operations_ section, operation is listed with start button
* Click on start and complete operation
* Now login  with user who has _Delivery manager_ role and click on _User Operations_

Notice that user is able to see the operation. It should not be seen as _Manager_ has not yet performed any action. 

User (with Delivery Manager role) should be able to see operation only when both (Team lead and Manager) have completed their action.

**Comment by madzhuga** [comment]
@waleedjaffar can you export and send me your process to check?

**Comment by madzhuga** [comment]
@waleedjaffar By default 'Approval by Delivery Manager' operation will be created if ANY of it's dependencies is satisfied. If you need both operations to be completed prior to this one - you need to use custom 'Approval by Delivery Manager' operation template class and override resolve_dependency method there to check if both operations completed in current process. Please let me know if you need more information

**Comment by madzhuga** [comment]
not an issue
