### ISSUE TITLE
Index name too long on rake db:migrate

### ISSUE THREAD

**Issue by dougfarre** [madzhuga/rails_workflow#11]
index name 'index_rails_workflow_operation_templates_on_process_template_id' on table 'rails_workflow_operation_templates' is too long; the limit is 62 characters/Users/dougf/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:936:in `add_index_options'

**Comment by madzhuga** [comment]
@dougfarre which db do you using?

**Comment by madzhuga** [comment]
@dougfarre is this issue still actual?

**Comment by madzhuga** [comment]
closing issue as have no responses

**Comment by jprosevear** [comment]
This is using sqlite during development.

**Comment by madzhuga** [comment]
@jprosevear I would say you better use something better than sqlite :) Better to use postgres
