### ISSUE TITLE
Expects User model to have role_text and group_text defined

### ISSUE THREAD

**Issue by chrisgogreen** [madzhuga/rails_workflow#12]
https://github.com/madzhuga/rails_workflow/blob/master/app/decorators/rails_workflow/operation_template_decorator.rb#L45-L46

I can't find where these are defined by rails_workflow, is there some configuration I am missing?

**Comment by madzhuga** [comment]
@chrisgogreen please take a look at test dummy app User model (https://github.com/madzhuga/rails_workflow/blob/master/spec/dummy/app/models/user.rb#L7) - it includes assignment + it has dummy methods for role_text and group_text.

**Comment by madzhuga** [comment]
@chrisgogreen is that issue still actual?

**Comment by NullVoxPopuli** [comment]
what if your app doesn't follow this user / role / group pattern?

**Comment by madzhuga** [comment]
Typically app uses roles / groups to define users which can pick up and complete an operation.  How would you define which users can / can't pick up and complete operation?
