### ISSUE TITLE
Error on Rake db:migration 

### ISSUE THREAD

**Issue by wolfieorama** [madzhuga/rails_workflow#13]
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_rails_workflow_operation_templates_on_process_template_id' on table 'rails_workflow_operation_templates' is too long; the limit is 62 characters/home/jmunyi/rails_play_ground/pinboard/db/migrate/20151117091953_create_workflow_processes.rb:38:in `block in create_indexes'

**Comment by madzhuga** [comment]
@wolfieorama What database do you use?

**Comment by wolfieorama** [comment]
@madzhuga  sorry my bad i was in the sqlite3 repo, let me try on pg

**Comment by Leon0824** [comment]
The same issue happens to MySQL.
> Index name 'index_rails_workflow_operation_templates_on_process_template_id' on table 'rails_workflow_operation_templates' is too long; the limit is 62 characters

**Comment by madzhuga** [comment]
@Leon0824 I will fix it today.

**Comment by madzhuga** [comment]
@Leon0824 I just pushed fix and published 0.4.1 gem version with this fix. Let me know if you have other problems.
