### ISSUE TITLE
postgres

### ISSUE THREAD

**Issue by wernerlaude** [madzhuga/rails_workflow#17]
Hi..thanks for your work.
I cant bundle install because it requires an installed postgres db which I don't want to install.
gem 'rails', '4.2.6'
gem 'rails_workflow', '0.3.1'

checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***

Would be great to have a choice.
Greetings 
Werner

**Comment by madzhuga** [comment]
@wernerlaude I will check today. Btw why do you use 0.3.1? Latest version is 0.3.7. I may be wrong but I think there was some dependencies removed after 0.3.1.

**Comment by wernerlaude** [comment]
Hi Maxim.

I first took this version as it is mentioned in your git repo.
Now I changed over to 0.3.7,
brew install postgres
initialized with mysql and got an error missing 
gem 'responders', '~> 2.0'
after bundling that I got it working..

Thanks so far..
Just to have a check it out would be great to just need a sqlite.. or so..

Anyway, it looks great.

Werner





> Am 15.03.2016 um 11:57 schrieb Maxim Madzhuga <notifications@github.com>:
> 
> @wernerlaude <https://github.com/wernerlaude> I will check today. Btw why do you use 0.3.1? Latest version is 0.3.7. I may be wrong but I think there was some dependencies removed after 0.3.1.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/madzhuga/rails_workflow/issues/17#issuecomment-196765159 <https://github.com/madzhuga/rails_workflow/issues/17#issuecomment-196765159>

Werner Laude - Ruby on Rails/WebDevelopment - München 
mail@laude.biz <mailto:mail@laude.biz> | +49 178 135 34 39 <tel:+49 178 135 34 39> | webagentur-laude.de <http://www.webagentur-laude.de/>

**Comment by madzhuga** [comment]
@wernerlaude it will not work with sqlite out of the box - currently migrations creates too long names for indexes or something of that kind - sqlite don't like long names :)

**Comment by wernerlaude** [comment]
right.. I failed that too

as I am traumatized ;-| with postgres usability I prefer mysql...

> Am 15.03.2016 um 12:12 schrieb Maxim Madzhuga <notifications@github.com>:
> 
> @wernerlaude <https://github.com/wernerlaude> it will not work with sqlite out of the box - currently migrations creates too long names for indexes or something of that kind - sqlite don't like long names :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/madzhuga/rails_workflow/issues/17#issuecomment-196768384 <https://github.com/madzhuga/rails_workflow/issues/17#issuecomment-196768384>

Werner Laude - Ruby on Rails/WebDevelopment - München 
mail@laude.biz <mailto:mail@laude.biz> | +49 178 135 34 39 <tel:+49 178 135 34 39> | webagentur-laude.de <http://www.webagentur-laude.de/>

**Comment by ahukkanen** [comment]
+1 for the database intependent database abstraction. I don't think the workflow system has any particula feature relying on postgres or mysql, so it would be great if it installed on SQLite too.

@madzhuga I would also remove the specific version number in the README installation guide since I also installed `0.3.1` at first when following the guide.

Also had the same problem with the `responders` gem as Werner above, so that would be good to document too. Or add to the gemfile if it's required with postgres as well.

**Comment by madzhuga** [comment]
@ahukkanen SQLite have no JSON support. JSON is used to store operations dependencies. Do you really planing to use SQLite as db for production application? 

I will update README shortly.

**Comment by ahukkanen** [comment]
But it [serializes the JSON data](https://github.com/madzhuga/rails_workflow/blob/12706c262a51f2ab2fdf7ba679387bc1eaaa45fa/app/models/rails_workflow/context.rb#L6) in case it's not supported, right? I haven't seen any direct queries using the JSON data, although haven't checked very deeply but it seemed the data would only be used directly in the JSON format.

Not really planning to use it in production but it would just make it simpler to install and try out locally. As I think the only problem seems to be the length of the index names. Eventhough, I wouldn't see it a problem using it even in production with some lower traffic services.

**Comment by madzhuga** [comment]
@wernerlaude in the past I added option to select MySQL dialect
`config.sql_dialect= 'mysql'` 
in configuration (you can find it's example in README.md)

**Comment by madzhuga** [comment]
@ahukkanen I have no plans to support SQLite. I don't think any big application having business logic complex enough to use rails_workflow will work on SQLite. :)

**Comment by ahukkanen** [comment]
@madzhuga That's fair and understand the extra work for the benefit.

But regarding using SQLite in production, I think Airbus is quite big and their A350 uses SQLite. So if you're afraid of using it in "big production applications", I would not board that airplane. :)
