### ISSUE TITLE
Use Active Job API

### ISSUE THREAD

**Issue by ahukkanen** [madzhuga/rails_workflow#19]
Instead of relying solely on Sidekiq regarding the background processing, I think it would be much more flexible regarding the selection of background processing system if Active Job was used (Rails 4.2+).

**Comment by madzhuga** [comment]
@ahukkanen will update it in a few days.

**Comment by madzhuga** [comment]
@ahukkanen I implemented Active Job API support here. Will be released with next version of gem or can be used already directly from master.

**Comment by ahukkanen** [comment]
:+1:

**Comment by ahukkanen** [comment]
Was it "open source" few days? :wink:

**Comment by madzhuga** [comment]
@ahukkanen yes, kind of :8ball:
