### ISSUE TITLE
support for sqlite3?

### ISSUE THREAD

**Issue by NullVoxPopuli** [madzhuga/rails_workflow#22]
default rails 5 app uses sqlite 3

**Comment by madzhuga** [comment]
@NullVoxPopuli I don't think big apps using such engines will use SQLite. Another thing to remember is that it has no JSON support, index names limitations and other things.

**Comment by madzhuga** [comment]
I am closing this issue as I don't think there is anything to fix. I still believe that none big application will use SQLite.
