### ISSUE TITLE
[FAQ] Production ready

### ISSUE THREAD

**Issue by kirantpatil** [madzhuga/rails_workflow#26]
Hi @madzhuga and rails_workflow community,

Is it production ready to use ?

Could you please share those who deployed in production, regarding any issue faced and so on ... ?

Thanks.

**Comment by madzhuga** [comment]
@kirantpatil I don't have a list of projects using it. There is one commercial project which uses custom version of it.

**Comment by kirantpatil** [comment]
IMHO, we should create wiki page with the list of projects who are using it.

**Comment by madzhuga** [comment]
:+1: I will create such wiki page when I will have know which projects to list there :)

**Comment by kirantpatil** [comment]
Thanks @madzhuga, we would like to join that elite group soon.

**Comment by madzhuga** [comment]
@kirantpatil can you describe application you using it for? :) Just curious.

**Comment by kirantpatil** [comment]
@madzhuga, we are planning to use it for Logistics app.

**Comment by madzhuga** [comment]
@kirantpatil sounds great! :) I used to work on Logistic project

**Comment by kirantpatil** [comment]
Sir. Is that project open source, so that we can use it ?

**Comment by madzhuga** [comment]
@kirantpatil sure it's open source and you can use it! :)

**Comment by kirantpatil** [comment]
@madzhuga can you please share the project link ?

**Comment by madzhuga** [comment]
@kirantpatil sorry, I thought you mean rails_workflow :) Logistic project I worked on is a private commercial product. :)

**Comment by kirantpatil** [comment]
Ok, thanks :)
