### ISSUE TITLE
undefined method `get_role_values'

### ISSUE THREAD

**Issue by sharat94** [madzhuga/rails_workflow#27]
![screenshot from 2017-02-28 17-42-57](https://cloud.githubusercontent.com/assets/20989907/23404907/6987ec72-fddd-11e6-9b4c-c34c8293a86b.png)

How is the roles for the template being taken? Iam using devise and cancancan gem in rails 5 and have got workflow running but it pops an error when i try to add person by role. Please help.

**Comment by madzhuga** [comment]
@sharat94 please check this [model](https://github.com/madzhuga/rails_workflow/blob/master/spec/dummy/app/models/user.rb).

**Comment by madzhuga** [comment]
By default, gem uses user.role or user.group for user operation authorization. Maybe it is better to make this functionality optional and just let any user pick any user operation by default, I haven't decided yet how to handle it better.

**Comment by madzhuga** [comment]
ps: Right now there are two types of user operations: user group operation and user role operation. User group operation allows only specified group users to complete an operation. User role operation same way allows only users with a specified role to complete an operation. I am going to add default user operation today - it will allow any user to pick up and complete operaiton.
