### ISSUE TITLE
Remove pg dependency

### ISSUE THREAD

**Issue by Leon0824** [madzhuga/rails_workflow#29]
Even though it is mentioned we can switch to `mysql` in the README, the pg dependency still be listed in the gemspec so we still must install PostgreSQL and pg gem. Could you consider remove pg dependency?

**Comment by madzhuga** [comment]
@Leon0824 I removed pg dependency from .gemspec - please update your app Gemfile with v. 0.4 - it should no longer require pg. I can't test it locally (don't want to remove local pg/Postgres to test it) so please let me know if it fixes this issue.

**Comment by Leon0824** [comment]
Yes, the `bundle install` works.
