### ISSUE TITLE
Issue in rake db:migrate

### ISSUE THREAD

**Issue by shubhamitc** [madzhuga/rails_workflow#3]
Issue with Json type column with PostgreSQL,

Stacktrace.......

singh@singh-Latitude-E5450:~/project/jen_etl/db/migrate$ bundle exec rake db:migrate --trace
(in /home/singh/project/jen_etl)
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
== 20150123172243 CreateWorkflowWfProcesses: migrating ========================
-- create_table(:workflow_processes)
   -> 0.0008s
-- create_table(:workflow_operations)
   -> 0.0005s
-- create_table(:workflow_process_templates)
   -> 0.0005s
-- create_table(:workflow_operation_templates)
   -> 0.0005s
-- add_column(:workflow_processes, :template_id, :integer)
   -> 0.0003s
-- add_column(:workflow_processes, :type, :string)
   -> 0.0002s
-- add_column(:workflow_operations, :process_id, :integer)
   -> 0.0003s
-- add_column(:workflow_operations, :template_id, :integer)
   -> 0.0002s
-- add_column(:workflow_operation_templates, :async, :boolean)
   -> 0.0003s
-- add_column(:workflow_operations, :dependencies, :text)
   -> 0.0002s
-- add_column(:workflow_operation_templates, :child_process_id, :integer)
   -> 0.0003s
-- add_column(:workflow_operations, :child_process_id, :integer)
   -> 0.0002s
-- add_column(:workflow_operation_templates, :assignment_id, :integer)
   -> 0.0002s
-- add_column(:workflow_operation_templates, :assignment_type, :string)
   -> 0.0002s
-- add_column(:workflow_operations, :assignment_id, :integer)
   -> 0.0002s
-- add_column(:workflow_operations, :assignment_type, :string)
   -> 0.0003s
-- add_column(:workflow_operations, :assigned_at, :datetime)
   -> 0.0002s
-- add_column(:workflow_operation_templates, :kind, :string)
   -> 0.0002s
-- add_column(:workflow_operation_templates, :role, :string)
   -> 0.0002s
-- add_column(:workflow_operation_templates, :group, :string)
   -> 0.0002s
-- add_column(:workflow_operations, :type, :string)
   -> 0.0002s
-- add_column(:workflow_operations, :is_active, :boolean)
   -> 0.0002s
-- add_column(:workflow_operation_templates, :instruction, :text)
   -> 0.0002s
-- create_table(:workflow_contexts)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `json' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x000000054940a8>/var/lib/gems/1.9.1/gems/rails_workflow-0.2.2/db/migrate/20150123172243_create_workflow_wf_processes.rb:66:in `block in change'
/var/lib/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:202:in `create_table'
/var/lib/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/var/lib/gems/1.9.1/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'

**Comment by madzhuga** [comment]
@shubhamitc, can you please run 
```
bundle exec rake about
```
and show me output?

**Comment by shubhamitc** [comment]
Hi Maxim,


Please find the details of rails, hopefully you can suggest something


singh@singh-Latitude-E5450:~/project/jen_etl$ bundle exec rake about

About your application's environment
Rails version             4.2.1
Ruby version              1.9.3-p484 (x86_64-linux)
RubyGems version          1.8.23
Rack version              1.5
JavaScript Runtime        therubyracer (V8)
Middleware                Rack::Sendfile, ActionDispatch::Static, Rack::Lock, #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x00000002320a08>, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, Rails::Rack::Logger, ActionDispatch::ShowExceptions, WebConsole::Middleware, ActionDispatch::DebugExceptions, ActionDispatch::RemoteIp, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::Migration::CheckPending, ActiveRecord::ConnectionAdapters::ConnectionManagement, ActiveRecord::QueryCache, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ParamsParser, Rack::Head, Rack::ConditionalGet, Rack::ETag
Application root          /home/singh/project/jen_etl
Environment               development
Database adapter          sqlite3
Database schema version   20150407144659

?Thanks,
Skype : annu.shubham



________________________________

**Comment by madzhuga** [comment]
@shubhamitc you using sqlite which has no json support. Json can be stored as string to sqlite and then parsed to json after loading from db (I have necessary code but it is not in master branch). Can you switch to postgres?

**Comment by shubhamitc** [comment]
Sure @maxim , I will check and get back to you.


________________________________

**Comment by shubhamitc** [comment]
?@maxim, getting different error now as I did setup a new environment ,


singh@singh-Latitude-E5450:~/project/rails_workflow/workflow$ bundle exec rake about
About your application's environment
Rails version             4.2.1
Ruby version              1.9.3-p484 (x86_64-linux)
RubyGems version          1.8.23
Rack version              1.5
Middleware                Rack::Sendfile, ActionDispatch::Static, Rack::Lock, #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x00000003453b40>, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, Rails::Rack::Logger, ActionDispatch::ShowExceptions, WebConsole::Middleware, ActionDispatch::DebugExceptions, ActionDispatch::RemoteIp, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::Migration::CheckPending, ActiveRecord::ConnectionAdapters::ConnectionManagement, ActiveRecord::QueryCache, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ParamsParser, Rack::Head, Rack::ConditionalGet, Rack::ETag
Application root          /home/singh/project/rails_workflow/workflow
Environment               development
Database adapter          postgresql
Database schema version   20150217161051
singh@singh-Latitude-E5450:~/project/rails_workflow/workflow$


Error ...........................................................

- column_exists?(:rails_workflow_processes, :updated_at)
   -> 0.0011s
-- column_exists?(:rails_workflow_processes, :template_id)
   -> 0.0011s
-- column_exists?(:rails_workflow_processes, :type)
   -> 0.0011s
rake aborted!
SyntaxError: /var/lib/gems/1.9.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/operations/assignments.rb:9: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG
        scope :by_role, -> (role) { joins(:template).wher...
                            ^
/var/lib/gems/1.9.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/operations/assignments.rb:9: syntax error, unexpected tLAMBEG, expecting keyword_end
...    scope :by_role, -> (role) { joins(:template).where(rails...
...                               ^
/var/lib/gems/1.9.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/operations/assignments.rb:9: syntax error, unexpected '}', expecting keyword_end
/var/lib/gems/1.9.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/operations/assignments.rb:10: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG
        scope :by_group, -> (group) { joins(:template).whe...
                             ^
/var/lib/gems/1.9.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/operations/assignments.rb:10: syntax error, unexpected tLAMBEG, expecting keyword_end
...  scope :by_group, -> (group) { joins(:template).where(rails...
...                               ^

?Thanks,




________________________________

**Comment by madzhuga** [comment]
You using ruby 1.9.3-p484 (x86_64-linux) - can you update it to ruby 2?

**Comment by shubhamitc** [comment]
@maxim, its not possible to download ruby in restrictive firewall access. I will give it a try once I reach home.

Hope it works.


Thanks,

________________________________

**Comment by shubhamitc** [comment]
@maxim, as per your suggestion upgrading to ruby-2.2.1 solved the migration issue, however now there is an issue to find the index template in predef dir.


Please suggest a workaround.


[cid:3d4ad9d4-d320-4b99-953e-6ce9b0cf7480]


________________________________
From: Shubhamkumar Singh
Sent: Wednesday, April 8, 2015 5:03 PM
To: madzhuga/rails_workflow; madzhuga/rails_workflow
Subject: RE: [rails_workflow] Issue in rake db:migrate (#3)


@maxim, its not possible to download ruby in restrictive firewall access. I will give it a try once I reach home.

Hope it works.


Thanks,

________________________________

**Comment by madzhuga** [comment]
can you please add exception stacktrace here?

**Comment by maxim** [comment]
@shubhamitc Hi there, you are referencing the wrong maxim, so I keep receiving notifications.

**Comment by shubhamitc** [comment]
@maxim,


Stacktrace ......................................


singh@singh-Latitude-E5450:~/project/rails_workflow$ rails s
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-04-09 13:45:56] INFO  WEBrick 1.3.1
[2015-04-09 13:45:56] INFO  ruby 2.2.1 (2015-02-26) [x86_64-linux]
[2015-04-09 13:45:56] INFO  WEBrick::HTTPServer#start: pid=12339 port=3000


Started GET "/workflow" for 127.0.0.1 at 2015-04-09 13:46:03 +0530
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by RailsWorkflow::OperationsController#index as HTML
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:31: warning: already initialized constant RailsWorkflow::Status::NOT_STARTED
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:31: warning: previous definition of NOT_STARTED was here
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:32: warning: already initialized constant RailsWorkflow::Status::IN_PROGRESS
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:32: warning: previous definition of IN_PROGRESS was here
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:33: warning: already initialized constant RailsWorkflow::Status::DONE
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:33: warning: previous definition of DONE was here
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:34: warning: already initialized constant RailsWorkflow::Status::WAITING
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:34: warning: previous definition of WAITING was here
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:35: warning: already initialized constant RailsWorkflow::Status::ERROR
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:35: warning: previous definition of ERROR was here
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:36: warning: already initialized constant RailsWorkflow::Status::CANCELED
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:36: warning: previous definition of CANCELED was here
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:37: warning: already initialized constant RailsWorkflow::Status::SKIPPED
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:37: warning: previous definition of SKIPPED was here
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:38: warning: already initialized constant RailsWorkflow::Status::ROLLBACK
/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:38: warning: previous definition of ROLLBACK was here
Completed 500 Internal Server Error in 43ms (ActiveRecord: 0.0ms)

ActionView::MissingTemplate (Missing template rails_workflow/operations/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder]}. Searched in:
  * "/home/singh/project/rails_workflow/app/views"
  * "/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/views"
):
  actionview (4.2.1) lib/action_view/path_set.rb:46:in `find'
  actionview (4.2.1) lib/action_view/lookup_context.rb:121:in `find'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:8:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  responders (2.1.0) lib/action_controller/responder.rb:236:in `default_render'
  responders (2.1.0) lib/action_controller/responder.rb:170:in `to_html'
  responders (2.1.0) lib/action_controller/responder.rb:163:in `respond'
  responders (2.1.0) lib/action_controller/responder.rb:156:in `call'
  responders (2.1.0) lib/action_controller/respond_with.rb:203:in `respond_with'
  rails_workflow (0.2.2) app/controllers/rails_workflow/operations_controller.rb:28:in `index'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'


  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.6ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/missing_template.html.erb within rescues/layout (20.0ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/web-console-2.1.2/lib/web_console/templates/_markup.html.erb (0.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/web-console-2.1.2/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/web-console-2.1.2/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/web-console-2.1.2/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/web-console-2.1.2/lib/web_console/templates/console.js.erb within layouts/javascript (13.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/web-console-2.1.2/lib/web_console/templates/main.js.erb within layouts/javascript (0.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/web-console-2.1.2/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/web-console-2.1.2/lib/web_console/templates/index.html.erb (28.5ms)

?



________________________________

**Comment by madzhuga** [comment]
@shubhamitc my bad. need to add slim dependencies :) 

add to your Gemfile
gem 'slim'
gem 'slim-rails'
- after that app will see slim templates (right now it searches erb etc templates).

**Comment by shubhamitc** [comment]
@maxim,


That solve the issue of slim however now I am having issues with bootstrap,


Stacktrace ...........................................


/usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/concerns/rails_workflow/status.rb:38: warning: previous definition of ROLLBACK was here
  RailsWorkflow::Operation Load (65.7ms)  SELECT "rails_workflow_operations".* FROM "rails_workflow_operations" WHERE "rails_workflow_operations"."status" = 3  ORDER BY "rails_workflow_operations"."created_at" DESC
  Rendered /usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/views/rails_workflow/operations/index.html.slim within layouts/rails_workflow/application (137.3ms)
Completed 500 Internal Server Error in 249ms (ActiveRecord: 86.6ms)

ActionView::Template::Error (couldn't find file 'bootstrap/bootstrap'
  (in /usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/assets/stylesheets/rails_workflow/application.css:13)):
     7:
     8:   title Rails Workflow Engine
     9:
    10:   = stylesheet_link_tag "rails_workflow/application"
    11:   = javascript_include_tag "rails_workflow/application"
    12:   = csrf_meta_tags
    13: ?


Thanks,

________________________________

**Comment by madzhuga** [comment]
add to your Gemfile
gem 'bootstrap-rails-engine'

**Comment by madzhuga** [comment]
will clean up dependencies like bottstrap-rails-engine shortly in next builds :(

**Comment by shubhamitc** [comment]
@maxim, Thanks for your help as GUI is working now. GUI looks good too.

Can you suggest how to make process tab work and add some operation, for now I am getting some exception for no pagination method in Process model.


Exception ,


undefined method `paginate' for #<RailsWorkflow::Process::ActiveRecord_Relation:0x007f3269362a48>


.................................


I am new to rails, and planning to create a tool which uses these features. Hope we both can help each other.


Thanks,

Skype : annu.shubham

________________________________

**Comment by madzhuga** [comment]
Use will_paginate gem

**Comment by shubhamitc** [comment]
Thanks @maxim, now I am getting different error while clicking user operation page ,


Showing /usr/local/rvm/gems/ruby-2.2.1/gems/rails_workflow-0.2.2/app/views/rails_workflow/operation_templates/_user_role_form.html.slim where line #13 raised:

uninitialized constant ActionView::CompiledTemplates::User

Extracted source (around line #13):

11
12
13
14
15
16



  = f.label :role, class: "control-label col-sm-2"

  .col-sm-10

    = f.collection_select(:role, User.get_role_values, :last, :first, {include_blank: true}, {class: "form-control"})



.form-group

  = f.label :title, class: "control-label col-sm-2"




Thanks,?



________________________________

**Comment by madzhuga** [comment]
use gem devise to generate user.

**Comment by kirantpatil** [comment]
Me too have the same issue while running the below command.

$ bundle exec rake db:migrate
.....
.....
-- add_column(:workflow_operations, :type, :string)
   -> 0.0003s
-- add_column(:workflow_operations, :is_active, :boolean)
   -> 0.0008s
-- add_column(:workflow_operation_templates, :instruction, :text)
   -> 0.0003s
-- create_table(:workflow_contexts)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `json' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x00000002d0fc30>/home/kpatil/.rvm/gems/ruby-2.2.2/gems/rails_workflow-0.2.2/db/migrate/20150123172243_create_workflow_wf_processes.rb:66:in `block in change'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:202:in `create_table'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'


System details:
[kpatil@dhcppc14 demo]$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
[kpatil@dhcppc14 demo]$ rails -v
Rails 4.2.1

**Comment by madzhuga** [comment]
what is your database?

**Comment by kirantpatil** [comment]
I think it is sqlite.

**Comment by kirantpatil** [comment]
Yes, it is sqlite.

**Comment by madzhuga** [comment]
@kirantpatil sqlite does not have json support.

**Comment by kirantpatil** [comment]
Ok, then I will install and use Postgresql.
