### ISSUE TITLE
Syntax error in latest rev.

### ISSUE THREAD

**Issue by MadPositron** [madzhuga/rails_workflow#33]
rails_workflow/operation_runner.rb

line 65: context&.save should be context.save

**Comment by madzhuga** [comment]
@MadPositron it's not a syntax error. Please check [this](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/)

**Comment by MadPositron** [comment]
Please define the minimum ruby version in your gemspec or Gemfie as your gem will break w/ any ruby < 2.3
