### ISSUE TITLE
Isn't working on Rails 5 

### ISSUE THREAD

**Issue by meysammeisam** [madzhuga/rails_workflow#34]
undefined method `before_filter' for `RailsWorkflow::OperationsController:Class`

**Comment by madzhuga** [comment]
@meysammeisam I will replace `before_filter` with `before_action` today. Thanks for reporting!

**Comment by madzhuga** [comment]
@meysammeisam I actually just replaced it. It is in master branch already and I will publish new gem version tomorrow - I am preparing events support and will publish new gem version shortly. Can you check the fix yourself?

**Comment by meysammeisam** [comment]
@madzhuga yes, thanks, I'll test it

**Comment by meysammeisam** [comment]
@madzhuga fixed, thanks :pray:

**Comment by madzhuga** [comment]
@meysammeisam thanks! :pray:
