### ISSUE TITLE
db:migrate error json

### ISSUE THREAD

**Issue by DigitalRecline** [madzhuga/rails_workflow#4]
Hi

I'm getting the following error when trying to migrate the database. Any ideas on how to solve this. All dependencies seem to be installed correctly. 

D:\Workspace\sad>bundle exec rake db:migrate
DL is deprecated, please use Fiddle
DL is deprecated, please use Fiddle
== 20150123172243 CreateWorkflowWfProcesses: migrating ========================
-- create_table(:workflow_processes)
   -> 0.0110s
-- create_table(:workflow_operations)
   -> 0.0050s
-- create_table(:workflow_process_templates)
   -> 0.0050s
-- create_table(:workflow_operation_templates)
   -> 0.0040s
-- add_column(:workflow_processes, :template_id, :integer)
   -> 0.0150s
-- add_column(:workflow_processes, :type, :string)
   -> 0.0150s
-- add_column(:workflow_operations, :process_id, :integer)
   -> 0.0180s
-- add_column(:workflow_operations, :template_id, :integer)
   -> 0.0140s
-- add_column(:workflow_operation_templates, :async, :boolean)
   -> 0.0140s
-- add_column(:workflow_operations, :dependencies, :text)
   -> 0.0130s
-- add_column(:workflow_operation_templates, :child_process_id, :integer)
   -> 0.0130s
-- add_column(:workflow_operations, :child_process_id, :integer)
   -> 0.0120s
-- add_column(:workflow_operation_templates, :assignment_id, :integer)
   -> 0.0130s
-- add_column(:workflow_operation_templates, :assignment_type, :string)
   -> 0.0110s
-- add_column(:workflow_operations, :assignment_id, :integer)
   -> 0.0120s
-- add_column(:workflow_operations, :assignment_type, :string)
   -> 0.0110s
-- add_column(:workflow_operations, :assigned_at, :datetime)
   -> 0.0100s
-- add_column(:workflow_operation_templates, :kind, :string)
   -> 0.0100s
-- add_column(:workflow_operation_templates, :role, :string)
   -> 0.0120s
-- add_column(:workflow_operation_templates, :group, :string)
   -> 0.0130s
-- add_column(:workflow_operations, :type, :string)
   -> 0.0120s
-- add_column(:workflow_operations, :is_active, :boolean)
   -> 0.0130s
-- add_column(:workflow_operation_templates, :instruction, :text)
   -> 0.0110s
-- create_table(:workflow_contexts)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `json' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x5edc6a0>D:in `migrate'
NoMethodError: undefined method `json' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x5edc6a0>
D:in `migrate'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
'

**Comment by madzhuga** [comment]
Hi @DigitalRecline 

Please make sure your db supports json data type. For example postgresql and mysql have json support while sqlite has no json supports.

**Comment by DigitalRecline** [comment]
Cheers for the quick reply. I'm using MySQL running with the mysql2 gem. is there anything that needs to be added for the json support?

**Comment by DigitalRecline** [comment]
Not to deep into project so switching to postgresSQL seemed to work fine.There seems to be something funky going on with it in mysql.
