### ISSUE TITLE
Missing template rails_workflow/operations/index

### ISSUE THREAD

**Issue by samnissen** [madzhuga/rails_workflow#6]
Following [these instructions](https://github.com/madzhuga/rails_workflow/issues/5), I get an error at localhost:3000/workflows/

```ruby
ActionView::MissingTemplate - Missing template rails_workflow/operations/index with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/path/app/views"
  * "/path/.rvm/gems/ruby-2.1.2/gems/rails_workflow-0.3.2/app/views"
  * "/path/.rvm/gems/ruby-2.1.2/gems/bootstrap-sass-extras-0.0.6/app/views"
  * "/path/.rvm/gems/ruby-2.1.2/bundler/gems/devise-aa49dd53b557/app/views"
```

There is a file `/path/.rvm/gems/ruby-2.1.2/gems/bootstrap-sass-extras-0.0.6/app/views/rails_workflow/operations/index.html.slim`. I'm unfamiliar with `.slim` templates, but I think rails_workflow must have an undocumented template handler dependency?

**Comment by madzhuga** [comment]
@samnissen I will check if

gem 'slim'
gem 'slim-rails'
are included in dependencies. Just add them to your Gemfile for now.

**Comment by madzhuga** [comment]
@samnissen can you try last version? It should fix that issue.

**Comment by samnissen** [comment]
@madzhuga I upgraded OS X and my setup has exploded (libv8 issue). I'm going to need a while to rebuild -- sorry.

**Comment by madzhuga** [comment]
@samnissen please let me know if you still facing this issue.

**Comment by samnissen** [comment]
This issue is fixed!
