### ISSUE TITLE
why aren't there more workflow gems?

### ISSUE THREAD

**Issue by daniely** [madzhuga/rails_workflow#9]
Hi @madzhuga just wondering if you have any idea why there aren't any good workflow gems? I'm sure that's why you started this project. But any ideas why gems like Stonepath and Ruote never took off?

It seems really odd to me since most project I work on always have some business process and I've never found a good way of managing them.

Is it because people are just using state machines to manage workflows? Or maybe a combination of service objects and state machines or something?

Anyway, curious to hear your thoughts!

Also, good luck on this project!

**Comment by madzhuga** [comment]
@daniely I think that it's easy to use some state machine at first, than they start using service objects and then start to realize that they need something else. I can't say why there is no good rails workflow gems. 

Why do you think Stonepath and Ruote nevere took off? I would say that Ruote is great but it's pure ruby.

**Comment by daniely** [comment]
My guess with stonepath and ruote is that they were hard to use and people couldn't understand why they were needed. Especially since people were getting confused between state machines and workflows - many people (including myself) thought they were the same thing.

But it's possible that people found other/simpler solutions to their workflow problems and went that route. I'm really not sure though and I'm still investigating.

My current project's workflow is simple enough that we're able to use state machines...at least for now.
